!function(d){d(document).ready(function(){function e(){s&&n(),a=setInterval(n,6e3),d("#timer-slider").addClass("active")}function t(){clearInterval(a),d("#timer-slider").removeClass("active")}function n(){c.slick("slickNext"),setTimeout(function(){o.slick("slickNext")},300)}function i(){r=r?(e(),!1):(t(),!0)}if(slick_lafab){var a,r=!1,s=!1,c=d("#slider-1").slick({fade:!0,arrows:!1}),o=d("#slider-2").slick({fade:!0,arrows:!1}),l=d("#reals-slideshow-1 .slider-content ul"),u=d("#reals-slideshow-2 .slider-content ul");c.on("beforeChange",function(e,n,i,t){if(l.find('[data-key="'+i+'"]').fadeOut(),l.find('[data-key="'+t+'"]').fadeIn(),d(window).innerWidth()<1130){
//console.log( $(window).innerWidth() );
var a=l.find('[data-key="'+t+'"]').height();d("#reals-slideshow-1 .slider-content").css("margin-bottom",a+"px")}}),o.on("beforeChange",function(e,n,i,t){u.find('[data-key="'+i+'"]').fadeOut(),u.find('[data-key="'+t+'"]').fadeIn()}),c.on("swipe",function(e,n,i){t()}),o.on("swipe",function(e,n,i){t()}),0<d("#timer-slider").length&&e(),d("#timer-slider").on("click",function(e){e.preventDefault(),i(),s=!0})}})}(jQuery),function(i){i(document).ready(function(){
//var openedSubMenu;
i("#main-nav").on("click",".has-children > a",function(e){e.preventDefault();var n=i(this).parent().children("ul");n.hasClass("open")?n.removeClass("open").hide():(i("#main-nav .has-children > ul.sub-menu").hide(),n.addClass("open").show())}),i("#under-menu-active").on("click",function(e){e.preventDefault(),
//alert("body clicked");
i(".hamburger").trigger("click")})})}(jQuery),function(){
// Look for .hamburger
var e=document.querySelector(".hamburger"),n=document.querySelector("#main-nav"),i=document.querySelector(".wrapper-hamburger"),t=document.getElementsByTagName("BODY")[0];
// On click
e.addEventListener("click",function(){e.classList.toggle("is-active"),n.classList.toggle("is-active"),i.classList.toggle("is-active"),t.classList.toggle("menu-active"),jQuery("#search-icon").removeClass("open"),jQuery("#wrapper-searchform").removeClass("open")})}(),function(e,n){e(n).ready(function(){e("#gform_wrapper_2").on("click",'#field_2_4 label[id*="label_2_4_"], #field_2_13 label[id*="label_2_13_"]',function(){e(this).toggleClass("selected")})})}(jQuery,document),function(n,e){n(e).ready(function(){n("#search-icon").on("click",function(e){e.preventDefault(),n(this).toggleClass("open"),n("#wrapper-searchform").toggleClass("open")})})}(jQuery,document);